# Generated by Django 3.2 on 2021-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.PositiveIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='contact_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
